[package]
name = "video_process"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env-libvpx-sys = { version = "5.1.1", features = ["generate"] }
rtp = { git = "https://github.com/Cassy343/rtp", branch = "code-improvements" }
bytes = "1.1.0"
dcv-color-primitives = "0.5.1"
thiserror = "1.0.31"
cfg-if = "1.0.0"
webrtc-util = "0.5.4"
num_cpus = "1.13.1"
fast_image_resize = "0.9.6"
webrtc-media = { git ="https://github.com/jbis9051/media" }

[dev-dependencies]
image = "0.24.2"