[package]
name = "native"
version = "0.0.0"
description = "Native library including bindings to screen, keyboard, and mouse APIs"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
errno = "0.2.8"
libc = "0.2.108"
thiserror = "1.0.30"

[build-dependencies]
cfg-if = "1.0.0"

[dependencies.image]
version = "0.23.14"
default-features = false


[target.'cfg(all(target_os="linux", not(dummy_native)))'.dependencies]
x11 = { version = "2.19.1", features = ["xtest"] }
x11-clipboard = "0.6.1"
xcb = { version = "1.1.1", features = ["shm", "xlib_xcb", "randr"] }

[target.'cfg(all(target_os="macos", not(dummy_native)))'.dependencies]
cocoa = "0.24.0"
cocoa-foundation = "0.1.0"
core-graphics = { version = "0.22.3", features = ["highsierra"] }
core-graphics-types = "0.1.1"
core-foundation = "0.9.2"
once_cell = "1.9.0"
objc = "0.2.7"
accessibility-sys = "0.1.3"
block = "0.1.6"
# Remove before merge
windows={version = "0.37.0", features =["Win32_Graphics_Gdi", "Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_System_DataExchange", "Win32_System_SystemServices", "Win32_System_Memory", "Win32_Storage_Xps", "Win32_System_SystemInformation", "Win32_Graphics_Dwm"]}

[target.'cfg(all(target_os="windows", not(dummy_native)))'.dependencies]
windows={version = "0.37.0", features =["Win32_Graphics_Gdi", "Win32_Foundation", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_System_DataExchange", "Win32_System_SystemServices", "Win32_System_Memory", "Win32_Storage_Xps", "Win32_System_SystemInformation", "Win32_Graphics_Dwm"]}
once_cell = "1.9.0"
