[package]
name = "capture"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = {path = "../common"}
native = {path = "../native"}
event_loop = {path = "../event_loop"}
crossbeam-channel = "0.5.5"
