[package]
name = "parser"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.34"
proc-macro-crate = "1.1.0"
quote = "1.0.10"
syn = { version = "1.0.83", features = ["parsing", "proc-macro"] }
