[package]
name = "node-interop"
version = "0.1.0"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.56"
common = { path = "../common" }
native = { path = "../native" }
event_loop = { path= "../event_loop" }
peer = { path = "../peer" }
capture ={path = "../capture"}
peer_util = {path ="../peer_util"}
io = {path = "../io"}
num-traits = "0.2.15"
crossbeam-channel = "0.5.2"
cfg-if = "1.0.0"

[dependencies.neon]
version = "0.10.0"
default-features = false
features = ["napi-6", "promise-api", "channel-api"]
