[workspace]
members = [
    "common",
    "native",
    "node-interop",
    "parser",
    "peer",
    "server"
]

[profile.release]
opt-level = 3
debug = 0
debug-assertions = false
overflow-checks = false

[profile.prod]
inherits = "release"
strip = "symbols"
lto = "fat"

[profile.profile]
inherits = "release"
debug = 2
