[package]
name = "common"
version = "0.0.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
parser = { path = "../parser" }
thiserror = "1.0.30"
chrono = "0.4.19"
hmac = "0.12.0"
blake3 = { git = "https://github.com/jbis9051/BLAKE3", features = ["traits-preview"] }
hkdf = { git = "https://github.com/jbis9051/KDFs" }
srp = { git = "https://github.com/jbis9051/PAKEs/" }