[package]
name = "common"
version = "0.0.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
byteorder = "1.4.3"
parser = { path = "../parser" }
thiserror = "1.0.30"
chrono = "0.4.19"
crossbeam-channel = "0.5.2"
hmac = "0.12.0"
blake3 = { version="1.3.1", features = ["traits-preview"] }
hkdf = "0.12.1"
srp = "0.6.0"
chacha20poly1305 = "0.9.0"