[package]
name = "native"
version = "0.0.0"
description = "Native library including bindings to screen, keyboard, and mouse APIs"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
cfg-if = "1.0.0"
thiserror = "1.0.30"

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6"]

[target.'cfg(unix)'.dependencies]
x11 = "2.19.1"
