[package]
name = "native"
version = "0.0.0"
description = "Native library including bindings to screen, keyboard, and mouse APIs"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
cfg-if = "1.0.0"
errno = "0.2.8"
libc = "0.2.108"
thiserror = "1.0.30"

[dependencies.image]
version = "0.23.14"
default-features = false
features = ["png"]

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6"]

[target.'cfg(unix)'.dependencies]
xcb = { version="1.0.0-beta.0", features=["shm"] }
