[package]
name = "screenview_native"
version = "0.1.0"
authors = ["jbis9051 <josh9051@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
