[package]
name = "native"
version = "0.0.0"
description = "Native library including bindings to screen, keyboard, and mouse APIs"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
cfg-if = "1.0.0"
errno = "0.2.8"
libc = "0.2.108"
thiserror = "1.0.30"

[build-dependencies]
cfg-if = "1.0.0"

[dependencies.image]
version = "0.23.14"
default-features = false
features = ["png"]

[dependencies.neon]
version = "0.9"
default-features = false
features = ["napi-6"]


[target.'cfg(target_os="linux")'.dependencies]
x11 = { version = "2.19.1", features = ["xtest"] }
x11-clipboard = "0.5.3"
xcb = { version = "1.0.0-beta.0", features = ["shm", "xlib_xcb", "randr"] }

[target.'cfg(target_os="macos")'.dependencies]
cocoa = "0.20.1"
cocoa-foundation = "0.1.0"
core-graphics = { version = "0.22.3", features = ["highsierra"] }
core-graphics-types = "0.1.1"
core-foundation = "0.9.2"
once_cell = "1.9.0"