name: Workspace
on:
  pull_request:
    paths-ignore:
      - README.md
  push:
    branches:
      - master
      - "feature/*"
    paths-ignore:
      - README.md

defaults:
  run:
    working-directory: packages/rust

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "--cfg dummy_native"

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          override: true
          profile: minimal
      - run: apt update
      - run: apt install libvpx6 -y
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
      - run: apt update
      - run: apt install libvpx6 -y
      - run: cargo test --tests
